profiles:
- args:
  - https://calendar.google.com/calendar
  - https://mail.google.com/mail/u/0
  - https://outlook.office.com/mail
  name: Z
- args:
  - https://web.whatsapp.com
  - https://www.instagram.com/direct/inbox
  - https://discord.com/channels/@me
  name: P
- args:
  - http://localhost:1313/mathwiki/downward_lowenheim-skolem_theorem
  - :set -u localhost:1313 input.mode_override passthrough
  - :set statusbar.show never
  - :mode-enter passthrough
  - :bind --mode=passthrough <Ctrl+o> undo
  - :bind --mode=passthrough <Ctrl+f> hint
  - :bind --mode=passthrough <Ctrl+u> cmd-repeat 20 scroll up
  - :bind --mode=passthrough <Ctrl+d> cmd-repeat 20 scroll down
  - :bind --mode=passthrough <Ctrl+w> tab-close
  - :bind --mode=passthrough <Ctrl+h> back
  - :bind --mode=passthrough <Ctrl+l> forward
  - :bind --mode=passthrough <Ctrl+j> tab-prev
  - :bind --mode=passthrough <Ctrl+k> tab-next
  - :bind --mode=passthrough <Ctrl+r> reload
  - -s
  - window.title_format
  - MathWiki
  name: M
