colors:
  primary:
    background: '0x1e2127'
    foreground: '0xa8a8aa'
    bright_foreground: '0xe6efff'
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'
  dim:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

font:
  normal:
    family: "Courier Prime"
    style: Regular
  bold:
    family: "Courier Prime"
    style: Bold
  italic:
    family: "Courier Prime"
    style: Italic
  bold_italic:
    family: "Courier Prime"
    style: Bold Italic

  size: 10

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

window:
  padding:
    x: 2
    y: 2

window.opacity: 1.0

scrolling:
  history: 10000
  multiplier: 10

draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
window.dynamic_title: true
