start-at-login = false
accordion-padding = 0
after-startup-command = [
    'exec-and-forget borders',
    'exec-and-forget sketchybar',
    'exec-and-forget skimUtils -d'
]

on-focus-changed = [
    'exec-and-forget /bin/bash -c "echo \"$(aerospace list-windows --focused --format %{app-name} 2>/dev/null)\" > /tmp/skim_focus_pipe"',
    'exec-and-forget /bin/bash -c "sketchybar --trigger aerospace_custom_app_switched INFO=\"$(aerospace list-windows --focused --format %{app-name} 2>/dev/null)\" TITLE=\"$(aerospace list-windows --focused --format %{window-title} 2>/dev/null)\""'
]

exec-on-workspace-change = [ '/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
    inner.horizontal  = 10
    inner.vertical    = 10
    outer.left        = 10
    outer.bottom      = 10
    outer.top         = 10
    outer.right       = 10

[mode.main.binding]
    cmd-backslash = 'exec-and-forget /etc/profiles/per-user/zhao/bin/alacritty'
    cmd-shift-backslash = 'exec-and-forget open -a finder'

    cmd-e = """exec-and-forget /etc/profiles/per-user/zhao/bin/alacritty \
        -e /bin/bash -c 'printf "\\033]0;vifm\\007"; \
        exec /etc/profiles/per-user/zhao/bin/vifm ~/ \
        -c ":vsplit" \
        -c "windo normal ggvGgA"'"""

    cmd-enter = [
        """exec-and-forget /etc/profiles/per-user/zhao/bin/alacritty \
            --config-file ~/.config/alacritty/launcher.toml \
            --title launcher \
            -e /etc/profiles/per-user/zhao/bin/launcher""",
        'mode launcher'
    ]

    cmd-t = """exec-and-forget /etc/profiles/per-user/zhao/bin/alacritty \
        --config-file ~/.config/alacritty/btop.toml \
        --title btop \
        --option "window.dimensions={columns=100,lines=35}" \
        --option "window.position={x=525,y=250}" \
        -e /etc/profiles/per-user/zhao/bin/btop"""

    cmd-g = """exec-and-forget /etc/profiles/per-user/zhao/bin/alacritty \
        --title git \
        --option "window.dimensions={columns=100,lines=35}" \
        --option "window.position={x=525,y=250}" \
        -e zsh -ic ~/iCloud/Dotfiles/modules/scripts/git.sh"""

    cmd-a = """exec-and-forget /etc/profiles/per-user/zhao/bin/alacritty \
        --title attic \
        --option "window.dimensions={columns=100,lines=35}" \
        --option "window.position={x=525,y=250}" \
        -e zsh -ic ~/iCloud/Dotfiles/modules/scripts/attic.sh"""

    cmd-shift-t = 'exec-and-forget open -a activity\ monitor'

    cmd-w       = [ 'workspace w', 'exec-and-forget open -a qutebrowser' ]
    cmd-shift-w = [ 'workspace w', 'exec-and-forget open -a safari' ]

    cmd-m       = [ 'workspace m', 'exec-and-forget open -a messages' ]
    cmd-s       = [ 'workspace m', 'exec-and-forget open -a music' ]
    cmd-shift-m = [ 'workspace m', 'exec-and-forget open -a mail' ]

    cmd-p = 'exec-and-forget screencapture ~/Downloads/Screenshot_$(date +%Y_%m_%d_%H%M%S).png'

    cmd-b       = "exec-and-forget blueutil --connect \"Zhaoshen's headphones\""
    cmd-shift-b = "exec-and-forget sh -c \"osascript -e 'tell application \\\"Music\\\" to pause'; blueutil --disconnect \\\"Zhaoshen's headphones\\\"\""

    cmd-h = 'focus left'
    cmd-j = 'exec-and-forget navigation down'
    cmd-k = 'exec-and-forget navigation up'
    cmd-l = 'focus right'

    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'
    cmd-shift-e = 'exec-and-forget navigation --enforce'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'

    cmd-f           = 'layout v_accordion v_tiles'
    cmd-shift-f     = 'macos-native-fullscreen'
    cmd-shift-space = 'layout floating tiling'
    cmd-tab         = 'focus --boundaries workspace --boundaries-action wrap-around-the-workspace dfs-next'
    cmd-r           = 'exec-and-forget /bin/bash -c "echo TOGGLE_STATE > /tmp/skim_focus_pipe"'

    cmd-shift-r = [
        'layout v_tiles',
        'flatten-workspace-tree',
        'exec-and-forget /bin/bash -c "echo DISABLE_STATE > /tmp/skim_focus_pipe"'
    ]

    cmd-esc = 'exec-and-forget navigation --close'
    cmd-q = 'exec-and-forget navigation --close'

[mode.launcher.binding]
    cmd-esc = [ 'close --quit-if-last-window', 'mode main' ]
    cmd-q = [ 'close --quit-if-last-window', 'mode main' ]
    ctrl-esc = [ 'close --quit-if-last-window', 'mode main' ]
    ctrl-q = [ 'close --quit-if-last-window', 'mode main' ]
    esc = [ 'close --quit-if-last-window', 'mode main' ]

[[on-window-detected]]
    if.app-id = 'org.qutebrowser.qutebrowser'
    run = 'move-node-to-workspace w'

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    run = 'move-node-to-workspace w'

[[on-window-detected]]
    if.app-id = 'com.apple.MobileSMS'
    run = 'move-node-to-workspace m'

[[on-window-detected]]
    if.app-id = 'com.apple.Music'
    run = 'move-node-to-workspace m'

[[on-window-detected]]
    if.app-id = 'com.apple.Mail'
    run = 'move-node-to-workspace m'

[[on-window-detected]]
    if.app-id = 'com.apple.SecurityAgent'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.ActivityMonitor'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.FaceTime'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'org.pqrs.Karabiner-EventViewer'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'net.sourceforge.skim-app.skim'
    run = ['exec-and-forget navigation --record $AEROSPACE_WINDOW_ID']

[[on-window-detected]]
    if.window-title-regex-substring = 'vifm-float'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'git'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'attic'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'ytMpv'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'launcher'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'btop'
    run = 'layout floating'
