start-at-login = false
after-startup-command = [
    'exec-and-forget nohup alacritty --daemon --socket /tmp/alacritty.sock > /dev/null 2>&1 &',
    'exec-and-forget open -g -a Skim',
    'exec-and-forget borders',
    'exec-and-forget sketchybar'
]

on-focus-changed = [
    'exec-and-forget /bin/bash -c "sketchybar --trigger aerospace_custom_app_switched INFO=\"$(aerospace list-windows --focused --format %{app-name} 2>/dev/null)\" TITLE=\"$(aerospace list-windows --focused --format %{window-title} 2>/dev/null)\""'
]

exec-on-workspace-change = [ '/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

accordion-padding = 0

[gaps]
    inner.horizontal  = 10
    inner.vertical    = 10
    outer.left        = 10
    outer.bottom      = 10
    outer.top         = 10
    outer.right       = 10

[mode.main.binding]
    # Terminal and finder
    cmd-backslash = 'exec-and-forget alacrittyDaemon'
    cmd-shift-backslash = 'exec-and-forget open -a finder'

    # Launcher
    cmd-enter = [
        '''exec-and-forget /bin/bash -c '
            ARGS=(
                "--title" "launcher"
                "--option" "window.dimensions={columns=120,lines=15}"
                "--option" "window.padding={x=20,y=25}"
                "--option" "window.position={x=275,y=400}"
                "--option" "font.offset={x=0,y=12}"
                "--option" "cursor.style={shape=\"Beam\",blinking=\"On\"}"
                "-e" "launcher"
            )
            alacrittyDaemon "${ARGS[@]}"
        ' ''',
        'mode launcher'
    ]

    # Vifm
    cmd-e = '''exec-and-forget /bin/bash -c '
        CMD="printf \"\033]0;vifm\007\"; exec vifm ~/ -c \":vsplit\" -c \"windo normal ggvGgA\""
        alacrittyDaemon -e /bin/bash -c "$CMD"
    ' '''

    # Btop
    cmd-t = '''exec-and-forget /bin/bash -c '
        ARGS=(
            "--title" "btop"
            "--option" "window.dimensions={columns=110,lines=38}"
            "--option" "window.position={x=425,y=246}"
            "--option" "keyboard.bindings=[{key=\"Q\",command={program=\"sh\",args=[\"-c\",\"aerospace close\"]}}]"
            "-e" "btop"
        )
        alacrittyDaemon "${ARGS[@]}"
    ' '''

    # Git
    cmd-g = '''exec-and-forget /bin/bash -c '
        ARGS=(
            "--title" "git"
            "--option" "window.dimensions={columns=110,lines=38}"
            "--option" "window.position={x=425,y=246}"
            "-e" "zsh" "-c" "$HOME/iCloud/Dotfiles/modules/scripts/git.sh"
        )
        alacrittyDaemon "${ARGS[@]}"
    ' '''

    # Attic
    cmd-a = '''exec-and-forget /bin/bash -c '
        ARGS=(
            "--title" "attic"
            "--option" "window.dimensions={columns=110,lines=38}"
            "--option" "window.position={x=425,y=246}"
            "-e" "zsh" "-c" "attic"
        )
        alacrittyDaemon "${ARGS[@]}"
    ' '''

    # Applications
    cmd-m       = [ 'exec-and-forget open -a messages',    'workspace m' ]
    cmd-s       = [ 'exec-and-forget open -a music',       'workspace m' ]
    cmd-shift-m = [ 'exec-and-forget open -a mail',        'workspace m' ]
    cmd-w       = [ 'exec-and-forget open -a qutebrowser', 'workspace w' ]
    cmd-shift-w = [ 'exec-and-forget open -a safari',      'workspace w' ]
    cmd-d       = [ 'exec-and-forget open -a Discord',     'workspace w' ]
    cmd-shift-t = 'exec-and-forget open -a activity\ monitor'

    # Screenshot
    cmd-p = 'exec-and-forget screencapture ~/Downloads/Screenshot_$(date +%Y_%m_%d_%H%M%S).png'

    # Skim
    cmd-shift-e = 'exec-and-forget skimUtils --enforceSkim'

    # Workspace/window focus
    # cmd-j = 'exec-and-forget skimUtils --switchFocus down'
    # cmd-k = 'exec-and-forget skimUtils --switchFocus up'
    cmd-j = 'focus down'
    cmd-k = 'focus up'
    cmd-h = 'focus left'
    cmd-l = 'focus right'
    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'

    # Workspace/window movement
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-h = 'move left'
    cmd-shift-l = 'move right'
    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'

    # Workspace/window management
    cmd-f           = 'layout v_accordion v_tiles'
    cmd-shift-f     = 'macos-native-fullscreen'
    cmd-shift-space = [ 'layout floating tiling', 'exec-and-forget /run/current-system/sw/bin/centerWindow' ]

    # Refresh workspace
    cmd-shift-r = [
        'layout v_tiles',
        'flatten-workspace-tree'
    ]

    # Close windows
    cmd-q = 'close'

[mode.launcher.binding]
    cmd-q = [ 'close', 'mode main' ]
    ctrl-q = [ 'close', 'mode main' ]

    cmd-esc = [ 'mode main' ]
    ctrl-esc = [ 'mode main' ]
    esc = [ 'mode main' ]

[[on-window-detected]]
    if.app-id = 'org.qutebrowser.qutebrowser'
    run = 'move-node-to-workspace w'

[[on-window-detected]]
    if.app-id = 'com.hnc.Discord'
    run = 'move-node-to-workspace w'

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    run = 'move-node-to-workspace w'

[[on-window-detected]]
    if.app-id = 'com.apple.MobileSMS'
    run = 'move-node-to-workspace m'

[[on-window-detected]]
    if.app-id = 'com.apple.Music'
    run = 'move-node-to-workspace m'

[[on-window-detected]]
    if.app-id = 'com.apple.Mail'
    run = 'move-node-to-workspace m'

[[on-window-detected]]
    if.app-id = 'com.apple.SecurityAgent'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.ActivityMonitor'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.FaceTime'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'org.pqrs.Karabiner-EventViewer'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'net.sourceforge.skim-app.skim'
    run = ['exec-and-forget skimUtils --recordSkim $AEROSPACE_WINDOW_ID']

[[on-window-detected]]
    if.window-title-regex-substring = 'git'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'attic'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'btop'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'ytMpv'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'launcher'
    run = 'layout floating'

[[on-window-detected]]
    if.window-title-regex-substring = 'vifm-float'
    run = 'layout floating'
